plugins {
    id 'java'
    id 'war'
}

group = 'com.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {

    // Servlet API
    // Tomcat 9이 실제 실행 시 제공하기 때문에 compileOnly 사용
    compileOnly 'javax.servlet:javax.servlet-api:4.0.1'

    // JSP API
    compileOnly 'javax.servlet.jsp:javax.servlet.jsp-api:2.3.3'

    // JSTL
    implementation 'javax.servlet:jstl:1.2'

    // PostgreSQL JDBC Driver
    implementation 'org.postgresql:postgresql:42.7.7'

    // Test
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}